[features]
seeds = false
skip-lint = false
[programs.localnet]
d_social_network = "DyZ8qnErBbmKqCW2X6Nj1Cat8imPjStjWu1cGwAAhLSQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kubo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
