[features]
seeds = false
skip-lint = false
[programs.localnet]
d_social_network = "5dgW78UWc7hT4jxgh4XYr4NN6rcqDUndg7JzzUeGCskL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kubo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
