[features]
seeds = false
skip-lint = false
[programs.localnet]
d_social_network = "c66C85hHCyaUJ6oYXdSRN381J1GY1Re2RTHkd8uis78"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kubo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
